[package]
name = "demo-app"
version = "0.1.0"
edition = "2021"

[dependencies]
autoken = { git = "https://github.com/Radbuglet/autoken.git", rev = "f02c8390ebd310e3f5679ffec2a31a1e6a217cbc" }
derive-where = "1.2.7"
generational-arena = "0.2.9"
macroquad = "0.4.5"
rustc-hash = "1.1.0"
